### ISSUE TITLE
Hide Screen Header

### ISSUE THREAD

**Issue by kennetpostigo** [callstackincubator/rebolt-navigation#117]
I think it would be better if we could just completely hide the header with maybe something like a `hidden` prop thats a boolean? Or just through hiding it with `headerStyle`? Makes the code more intuitive and less verbose than trying to render a custom header and rendering a null element. Thoughts?

**Comment by kennetpostigo** [comment]
This seems like the same issue in #77

**Comment by knowbody** [comment]
ok, so closing in favor of #77
